import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaCartPlus } from "react-icons/fa";
import { GoPerson } from "react-icons/go";
import Footer from "./MainComponents/Footer";
import { IoSearchOutline } from "react-icons/io5";
import LandingPage from "./MainComponents/LandingPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <div className="fixed flex justify-between items-center top-0 z-10 mb-[7rem] bg-green-400 w-full h-[4.5rem]">

          {/* logo */}
          <h1 className="text-3xl font-semibold px-4">Divyam Singh</h1>

          {/* middle content */}
          <ul className="flex">
            <li className="mr-4">
              <Link href="/Home">Home</Link>
            </li>
            <li>
              <Link href="/About">About</Link>
            </li>
            <li>
              <Link href="/Signup">Signup</Link>
            </li>
          </ul>

          {/* right content */}
          <ul className=" relative flex justify-center items-center px-4 gap-4">
          <input 
              type="text" 
              className=" md:w-[10rem] relative h-8 border rounded-lg px-4 "
              
              />
            <IoSearchOutline className=" absolute left-[9rem] font-bold"/>
            <FaCartPlus />
            <GoPerson />
           
          </ul>
        </div>
        <div className="pt-[4.5rem]">
          {children}

          <LandingPage/>

        {/* footer */}
         <Footer/>
        </div>
      </body>
    </html>
  );
}
